# Clearly Define Factor Universe

## 5 factor fama french from wrds

Size factor: smb

Value: hml (Book-to-market)

Profitability and Investment Factors: rmw (Robust minus weak profitability). cma (Conservative minus aggressive investment)

Momentum Factor: umd (Momentum)

Market Factor: mktrf (Market excess returns)

## from ken.french

https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html 

Value/Growth Factors: E/P (Earnings/price), CF/P (Cashflow/Price), D/P (Dividend Yield), Net Share Issues
Quality: Operating Profitability, Investment, Accruals
Risk: Market Beta， Daily Variance, and Daily Residual Variance
reversal: short-term reversal, long-term reversal

# Gather and Prepare Factor Data

Obtain monthly returns for all factors from WRDS.

Ensure each factor series is clean and correctly aligned with dates.

Standardize factors if needed (e.g., mean-zero, unit-variance for statistical stability).

In [1]:
import pandas as pd

PATH = '../_data/'

In [2]:
# from ken-fama
LT_Reversal = pd.read_csv(PATH + 'F-F_LT_Reversal_Factor.csv').set_index('date')
ST_Reversal = pd.read_csv(PATH + 'F-F_ST_Reversal_Factor.csv').set_index('date')
AC = pd.read_csv(PATH + 'Portfolios_Formed_on_AC.csv').set_index('date')
BETA = pd.read_csv(PATH + 'Portfolios_Formed_on_BETA.csv').set_index('date')
CFP = pd.read_csv(PATH  + 'Portfolios_Formed_on_CF-P_Wout_Div.csv').set_index('date')
DP = pd.read_csv(PATH  + 'Portfolios_Formed_on_D-P_Wout_Div.csv').set_index('date')
EP = pd.read_csv(PATH  + 'Portfolios_Formed_on_E-P_Wout_Div.csv').set_index('date')
NI = pd.read_csv(PATH  + 'Portfolios_Formed_on_NI.csv').set_index('date')
RESVAR = pd.read_csv(PATH + 'Portfolios_Formed_on_RESVAR.csv').set_index('date')
VAR = pd.read_csv(PATH  + 'Portfolios_Formed_on_VAR.csv').set_index('date')

In [3]:
# from wrds 5 fct + mom
df_5fct = pd.read_csv(PATH + 'famafrench_5fct_momentum_monthly.csv').set_index('date')
df_5fct.tail()

             mktrf     smb     hml     rmw     cma     umd      rf
date
2024-08-01  0.0161 -0.0355 -0.0110  0.0075  0.0082  0.0481  0.0048
2024-09-01  0.0173 -0.0092 -0.0277  0.0018 -0.0029 -0.0062  0.0040
2024-10-01 -0.0100 -0.0088  0.0086 -0.0142  0.0098  0.0296  0.0039
2024-11-01  0.0649  0.0460  0.0015 -0.0230 -0.0205  0.0101  0.0040
2024-12-01 -0.0315 -0.0383 -0.0300  0.0190 -0.0121 -0.0030  0.0037

In [4]:
dict_ = {'AC': AC, 'BETA': BETA, 'CFP':CFP, 'DP': DP, 'EP': EP, 'NI': NI, 'RESVAR': RESVAR, 'VAR':VAR}

df_10 = pd.DataFrame()
df_20 = pd.DataFrame()

for fct in dict_.keys():
    df = dict_[fct]
    s_20 = df['Hi 20'] - df['Lo 20']
    s_10 = df['Hi 10'] - df['Lo 10']
    s_20.name = fct
    s_10.name = fct
    
    df_20 = pd.concat([df_20, s_20], axis = 1)
    df_10 = pd.concat([df_10, s_10], axis = 1)
    
df_10 = pd.concat([df_10, LT_Reversal, ST_Reversal, df_5fct], axis = 1)
df_20 = pd.concat([df_20, LT_Reversal, ST_Reversal, df_5fct], axis = 1)

In [5]:
# df_10 (deciles) hi10 - lo10
df_10.tail()

,AC,BETA,CFP,DP,EP,NI,RESVAR,VAR,LT_Rev,ST_Rev,mktrf,smb,hml,rmw,cma,umd,rf
2024-08-01,0.0123,-0.1180,-0.0500,-0.0138,-0.0617,-0.0362,-0.0423,-0.0718,0.0071,0.0014,0.0161,-0.0355,-0.0110,0.0075,0.0082,0.0481,0.0048
2024-09-01,-0.0516,0.1273,-0.0226,-0.0026,-0.0263,-0.0009,0.0105,0.0169,-0.0025,0.0060,0.0173,-0.0092,-0.0277,0.0018,-0.0029,-0.0062,0.0040
2024-10-01,-0.0395,-0.0001,0.0053,-0.0023,-0.0120,0.0281,0.0370,0.0896,0.0182,-0.0150,-0.0100,-0.0088,0.0086,-0.0142,0.0098,0.0296,0.0039
2024-11-01,-0.0270,0.2593,0.0160,0.0023,0.0566,0.0434,0.2005,0.2245,0.0069,-0.0484,0.0649,0.0460,0.0015,-0.0230,-0.0205,0.0101,0.0040
2024-12-01,0.0161,0.1215,-0.0510,-0.0689,-0.0400,-0.0279,0.0804,0.0708,-0.0164,0.0036,-0.0315,-0.0383,-0.0300,0.0190,-0.0121,-0.0030,0.0037

In [6]:
# df_20 (quintiles) hi20 - lo20
df_20.tail()

,AC,BETA,CFP,DP,EP,NI,RESVAR,VAR,LT_Rev,ST_Rev,mktrf,smb,hml,rmw,cma,umd,rf
2024-08-01,0.0086,-0.0798,-0.0098,-0.0002,0.0046,-0.0129,-0.0392,-0.0239,0.0071,0.0014,0.0161,-0.0355,-0.0110,0.0075,0.0082,0.0481,0.0048
2024-09-01,-0.0260,0.0772,-0.0365,-0.0058,-0.0474,-0.0023,0.0605,0.0371,-0.0025,0.0060,0.0173,-0.0092,-0.0277,0.0018,-0.0029,-0.0062,0.0040
2024-10-01,-0.0289,0.0113,0.0077,0.0150,0.0240,0.0393,0.0031,0.0386,0.0182,-0.0150,-0.0100,-0.0088,0.0086,-0.0142,0.0098,0.0296,0.0039
2024-11-01,-0.0114,0.2044,0.0096,0.0036,0.0300,0.1048,0.1448,0.0414,0.0069,-0.0484,0.0649,0.0460,0.0015,-0.0230,-0.0205,0.0101,0.0040
2024-12-01,-0.0060,0.0631,-0.0819,-0.0669,-0.0700,0.0011,0.0248,0.0337,-0.0164,0.0036,-0.0315,-0.0383,-0.0300,0.0190,-0.0121,-0.0030,0.0037

# Initial Factor Diagnostics and Stationarity Checks

Conduct ADF (Augmented Dickey-Fuller) and KPSS tests to verify time stationarity.

Drop or adjust factors with serious non-stationary issues.

In [7]:
from statsmodels.tsa.stattools import adfuller

In [8]:
def adf_test_factors_df(factors_df, alpha=0.05):
    cols = ['ADF', 'pvalue', 'usedlag', 'nobs', 'critical_values', 'icbest', 'null']
    adf_results_df = pd.DataFrame(columns=cols)

    for factor in factors_df.columns:
        series = factors_df[factor].dropna()

        try:
            adf_result = adfuller(series, autolag='AIC', regression='c')
            adf, pval, usedlag, nobs, critical_values, icbest = adf_result
            critical_value_5 = critical_values['5%']

            # null = False --> reject H0 --> no unitroot --> time stationary
            null_hypothesis = pval >= alpha

            adf_results_df.loc[factor] = [
                round(adf, 4),
                round(pval, 4),
                usedlag,
                nobs,
                round(critical_value_5, 4),
                icbest,
                null_hypothesis
            ]
        except Exception as e:
            adf_results_df.loc[factor] = [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, f'Error: {e}']

    adf_results_df.index.name = 'Factor'

    return adf_results_df

In [9]:
adf_test_factors_df(df_10, alpha=0.05)

            ADF  pvalue  usedlag  nobs  critical_values       icbest   null
Factor
AC      -6.0881  0.0000        3   176          -2.8781  -703.307899  False
BETA    -3.8266  0.0026        5   174          -2.8783  -348.954570  False
CFP     -6.9027  0.0000        3   176          -2.8781  -403.287141  False
DP      -6.1954  0.0000        5   174          -2.8783  -510.199733  False
EP      -6.9837  0.0000        2   177          -2.8780  -442.641901  False
NI     -12.0643  0.0000        0   179          -2.8778  -539.464665  False
RESVAR  -4.7062  0.0001        4   175          -2.8782  -395.315849  False
VAR    -12.6892  0.0000        0   179          -2.8778  -354.215171  False
LT_Rev  -7.9833  0.0000        1   178          -2.8779  -690.718623  False
ST_Rev -11.6290  0.0000        1   178          -2.8779  -689.864121  False
mktrf  -11.2465  0.0000        1   178          -2.8779  -570.560689  False
smb    -14.2267  0.0000        0   179          -2.8778  -715.440465  False
hml    -11.6280  0.0000        0   179          -2.8778  -652.826818  False
rmw     -3.3178  0.0141       11   168          -2.8789  -842.470164  False
cma     -6.3695  0.0000        4   175          -2.8782  -804.384147  False
umd    -14.8697  0.0000        0   179          -2.8778  -624.302070  False
rf      -1.3532  0.6045        4   175          -2.8782 -2343.971275   True

In [10]:
adf_test_factors_df(df_20, alpha=0.05)

            ADF  pvalue  usedlag  nobs  critical_values       icbest   null
Factor
AC      -6.0413  0.0000        3   176          -2.8781  -800.749259  False
BETA    -3.9779  0.0015        5   174          -2.8783  -438.139194  False
CFP    -10.0123  0.0000        1   178          -2.8779  -486.859586  False
DP      -6.6069  0.0000        2   177          -2.8780  -580.179571  False
EP      -6.8191  0.0000        2   177          -2.8780  -494.639860  False
NI     -12.2574  0.0000        0   179          -2.8778  -578.319792  False
RESVAR  -9.0873  0.0000        2   177          -2.8780  -458.070325  False
VAR    -13.1494  0.0000        0   179          -2.8778  -417.389258  False
LT_Rev  -7.9833  0.0000        1   178          -2.8779  -690.718623  False
ST_Rev -11.6290  0.0000        1   178          -2.8779  -689.864121  False
mktrf  -11.2465  0.0000        1   178          -2.8779  -570.560689  False
smb    -14.2267  0.0000        0   179          -2.8778  -715.440465  False
hml    -11.6280  0.0000        0   179          -2.8778  -652.826818  False
rmw     -3.3178  0.0141       11   168          -2.8789  -842.470164  False
cma     -6.3695  0.0000        4   175          -2.8782  -804.384147  False
umd    -14.8697  0.0000        0   179          -2.8778  -624.302070  False
rf      -1.3532  0.6045        4   175          -2.8782 -2343.971275   True

# Estimate Stock Factor Loadings (First Step of Fama-MacBeth)

Run time-series regressions for each stock in your ETF portfolio (e.g., VHT) separately

Get beta loadings (β) for each stock on each factor. Each stock has a vector of factor loadings.

In [11]:
vht_rtn = pd.read_parquet(PATH + 'vht_mon_returns.parquet').pivot_table(index = 'mthcaldt', columns = 'ticker', values = 'mthret')

In [12]:
# adjust index to each trading calendar date (end of month)
fct_10 = df_10.copy()
fct_10.index = vht_rtn.index

fct_20 = df_20.copy()
fct_20.index = vht_rtn.index

# excess return
rtn = vht_rtn.apply(lambda x: x-fct_10['rf'], axis = 0)

# drop rf in fct dataframe
fct_10.drop(columns = ['rf'], inplace = True)
fct_20.drop(columns = ['rf'], inplace = True)

In [ ]:
import pandas as pd
import sys
sys.path.append("../src")

from fama_macbeth import FamaMacBethRolling, shanken_correction
from fama_macbeth_package import FamaMacBethRollingLM, shanken_correction_LM

y = rtn
x = fct_10
window = 60  # e.g. 60-month rolling window

In [14]:
# Old
fmb_old = FamaMacBethRolling(dependent=y, exog=x, window=window)
results_old = fmb_old.fit()

# Shanken correction (old)
shanken_old = shanken_correction(results_old)

# before shanken correction
factor_premium = results_old['factor_premiums']
factor_premium.name = 'fct_premium'
t_stat = results_old['t_stats']
t_stat.name = 't_stat'
p_values = pd.Series(results_old['p_values'], index = factor_premium.index)
p_values.name = 'p_values'

# after shanken correction
corrected_t_stats = pd.Series(shanken_old['corrected_t_stats'], index = factor_premium.index)
corrected_t_stats.name = 'corrected_t_stats'
corrected_p_values = pd.Series(shanken_old['corrected_p_values'], index = factor_premium.index)
corrected_p_values.name = 'corrected_p_values'

# result
old_version_result = pd.concat([factor_premium, t_stat, p_values, corrected_t_stats, corrected_p_values], axis = 1)

In [15]:
old_version_result

        fct_premium    t_stat  p_values  corrected_t_stats  corrected_p_values
AC         0.000948  0.262099  0.793699           0.131369            0.895705
BETA       0.004869  0.510712  0.610499           0.451031            0.652788
CFP       -0.011979 -1.172550  0.243318          -1.088509            0.278570
DP        -0.002735 -0.481221  0.631243          -0.342401            0.732653
EP        -0.010874 -1.232655  0.220134          -1.059208            0.291650
NI         0.005635  1.035278  0.302638           0.729288            0.467259
RESVAR     0.002390  0.305519  0.760504           0.212406            0.832154
VAR        0.002173  0.258478  0.796485           0.183889            0.854414
LT_Rev     0.000816  0.238029  0.812268           0.079628            0.936667
ST_Rev    -0.001070 -0.304271  0.761453          -0.149243            0.881615
mktrf      0.001379  0.274380  0.784268           0.189860            0.849743
smb       -0.000375 -0.121214  0.903726          -0.037901            0.969830
hml        0.000284  0.077805  0.938114           0.030973            0.975343
rmw        0.001297  0.559273  0.577027           0.099846            0.920635
cma       -0.001021 -0.405261  0.686013          -0.070960            0.943548
umd        0.000974  0.228284  0.819817           0.141516            0.887702

In [ ]:
# new (using linearmodels famamacbeth package)
fmb_new = FamaMacBethRollingLM(dependent=y, factors=x, window=window)
results_new = fmb_new.fit()

# Shanken correction
shanken_new = shanken_correction_LM(results_new)

# before shanken correction
factor_premium = results_new['factor_premiums']
factor_premium.name = 'fct_premium'
t_stat = results_new['t_stats']
t_stat.name = 't_stat'
p_values = pd.Series(results_new['p_values'], index = factor_premium.index)
p_values.name = 'p_values'

# after shanken correction
corrected_t_stats = pd.Series(shanken_new['corrected_t_stats'], index = factor_premium.index)
corrected_t_stats.name = 'corrected_t_stats'
corrected_p_values =  pd.Series(shanken_new['corrected_p_values'], index = factor_premium.index)
corrected_p_values.name = 'corrected_p_values'

# results
new_version_result = pd.concat([factor_premium, t_stat, p_values, corrected_t_stats, corrected_p_values], axis = 1)

In [17]:
new_version_result

        fct_premium    t_stat  p_values  corrected_t_stats  corrected_p_values
AC         0.000257  0.070456  0.943949           0.035537            0.971711
BETA       0.010259  1.089527  0.278123           0.959250            0.339378
CFP       -0.013834 -1.359977  0.176408          -1.261494            0.209598
DP        -0.005902 -1.065031  0.289018          -0.747825            0.456041
EP        -0.011587 -1.308476  0.193234          -1.125062            0.262827
NI         0.007633  1.406056  0.162313           0.988415            0.324955
RESVAR     0.006948  0.885652  0.377591           0.616176            0.538955
VAR        0.007474  0.882000  0.379555           0.629480            0.530241
LT_Rev     0.001339  0.390548  0.696830           0.130543            0.896357
ST_Rev     0.000831  0.240091  0.810673           0.116221            0.907673
mktrf      0.008264  1.822008  0.070965           1.191064            0.235999
smb        0.001645  0.530642  0.596656           0.166062            0.868390
hml       -0.000306 -0.083870  0.933301          -0.033351            0.973451
rmw        0.000698  0.301741  0.763376           0.053683            0.957278
cma       -0.001542 -0.608395  0.544085          -0.107015            0.914957
umd        0.000004  0.000956  0.999239           0.000594            0.999527