## Momentum Factors
#### WRDS Data:
WRDS gives us access to a number of global momentum factors, some of the descriptions are not particularly exhaustive so a few of the factors will have poor descriptions. 

https://wrds-www.wharton.upenn.edu/pages/get-data/contributed-data-forms/global-factor-data/?saved_query=6099113
- **ret_12_0**: Momentum 0-12 Months
- **ret_9_0**: Momentum 0-9 Months
- **ret_6_0**: Momentum 0-6 Months
- **ret_3_0**: Momentum 0-3 Months
- **ret_2_0**: Momentum 0-2 Months
- **ret_3_1**: Momentum 1-3 Months
- **ret_6_1**: Momentum 1-6 Months
- **ret_9_1**: Momentum 1-9 Months
- **ret_12_1**: Momentum 1-12 Months
- **ret_12_7**: Momentum 7-12 Months
- **ret_18_1**: Momentum 1-18 Months
- **ret_24_1**: Momentum 1-24 Months
- **ret_36_1**: Momentum 1-36 Months
- **ret_48_1**: Momentum 1-48 Months
- **ret_60_1**: Momentum 1-60 Months
- **ret_24_12**: Momentum 12-24 Months
- **ret_36_12**: Momentum 12-36 Months
- **ret_48_12**: Momentum 12-48 Months
- **ret_60_36**: Momentum 36-60 Months
- **umd**: Fama-French Momentum Factor (just downloaded from fama-french website)
- ****:

#### AQR Data:
The following three factors are all construced by AQR via a process of stock selection partially based off of market cap, and then by building the index out of the top 33% of stocks within their selected universe. Universe selections are remade every quarter. 

https://www.aqr.com/Insights/Datasets/Momentum-Indices-Monthly
- **aqr_mi**: The AQR Momentum Index (Large-Cap and Mid-Cap U.S. Equities)
- **aqr_scmi**: The AQR Small Cap Momentum Index (Small-Cap U.S. Equities)
- **aqr_imi**: The AQR International Momentum Index (Non-U.S. Equities)

#### Technical Indicators:
The following factors are all technical indicators of momentum calculated for the ETF, VHT. This is the ETF that has determined our investable universe, and so by calculating these technical indicators for the ETF as a whole they can serve as 'global' momentum indicators. 

This paper suggests four different ways to measure momentum in a financial setting all derived from a simple physics definition of momentum, $p = mv$. The paper makes an argument for using the EOD log differences in price as a measure of 'velocity', and suggests three different measures for mass: bid-ask spread, turnover rate, and volume. For this, we will only be considering turnover rate and volume due to lack of data availability for bid-ask spread. *PhysicsMomentum.pdf*
- **p_0**: This approach assumes unit mass $p^{(0)}(t) = \sum_{i=0}^{k-1} v(t - i)$

- **p_1**: This approach is remanicient of the traditional momentum definition, $p^{(1)}(t) = \sum_{i=0}^{k-1} m(t - i)v(t - i)$

- **p_2**: This approach is closer to how we might calculate the movement of the center of mass of an object, $p^{(2)}(t) = \frac{\sum_{i=0}^{k-1} m(t - i)v(t - i)}{\sum_{i=0}^{k-1} m(t - i)}$

- **p_3**: $p^{(3)}(t) = \frac{\mu(v(t - k + 1), \ldots, v(t))}{\sigma(v(t - k + 1), \ldots, v(t))}$


Others
- **rsi**: Relative Strength Indicator (RSI)
- **macd**: Moving Average Convergence Divergence (MACD)
- **adx**: Average Directional Index (ADX)
- **egr**: Earnings Growth Rate
- **mom_acc**: Momentum Acceleration
- **cci**: Commodity Channel Index (CCI)

In [3]:
import pandas as pd


DATA_DIR =  './FACTORANALYSIS/_data'

mom_data = pd.read_parquet(r'C:\Users\SalRe\OneDrive\Documents\GitHub\MSFM\Summer Externship\FactorAnalysis\_data\momentum_factors.parquet')
mom_data.head()
# Reach out to WRDS Help Desk to set up PGF File

                ema_30     ema_200       p_0  ...  ret_48_1  ret_60_1  ret_60_36
Date                                          ...
2015-03-31  132.750941  121.770984  0.615787  ...  1.351168  1.533445   0.233448
2015-04-30  135.513807  124.568169  0.609215  ...  1.240905  1.641219   0.262824
2015-06-30  138.815875  129.177150  0.669284  ...  1.302637  1.991343   0.418992
2015-07-31  141.153210  131.630975  0.624312  ...  1.398412  1.965416   0.414058
2015-08-31  141.402593  133.632003  0.527687  ...  1.552594  2.114438   0.467812

[5 rows x 42 columns]

## Initial Factor Diagnostics and Stationarity Checks

Conduct ADF (Augmented Dickey-Fuller) and KPSS tests to verify time stationarity.


Drop or adjust factors with serious non-stationary issues.

In [ ]:
# ADF Test should be conducted twice, first when we have the raw series, and second after we take diff()
# How to detect if there is an overall trend to the data without doing it manually. 
# Daily returns for the SQL query, see the other jupyter notebook. 
# Refer to MSA notes for lambda parameter tuning. 
# for the grid search we will evaluate via IC or sharpe. 
import yfinance as yf
from statsmodels.tsa.stattools import adfuller
from preprocessing import Preprocessor
import pandas as pd 
from settings import config
import numpy as np

def adf_test(df,map_df,trend_id = None,alpha=0.05, second_pass = False ):
    # Divide series into one that has a trend and one that does not. 
    # After differencing we should be running adf on regression ='c'
    
    cols = ['ADF','pvalue','usedlag','nobs','critical_values','icbest']

    adf_df = pd.DataFrame(columns = cols)
    for id in df.columns.tolist():
        series = df[id].dropna()

        if second_pass:
            reg = 'c'
        else: 
            reg = 'ct' if trend_id is not None and id in trend_id else 'c'
        try:
            result = adfuller(series, regression=reg, maxlag=1, autolag = 't-stat')
            adf, pval, lag, nobs, crit_vals, icbest = result
            cv = crit_vals[f"{int(alpha*100)}%"]
            adf_df.loc[id] = [adf,pval,lag,nobs,cv,icbest]

        except Exception as e:
            print(f"[{id}] ADF test failed: {e}")
            continue

    adf_df['null'] = np.where(adf_df['pvalue']<alpha,True,False) # if it's true then its stationary
    # adf_df['desc'] = adf_df.index.map(map_df.set_index('id')['title'])
    # adf_df['units_short'] = adf_df.index.map(map_df.set_index('id')['units_short'])
    adf_df = adf_df.sort_values(by='pvalue',ascending=False)
    return adf_df 

def difference(df,adf_df):
    # Difference the series if not stationary. Log differencing for levels and differencing for rates.
    # If adf test is rejected then we are accepting hypothesis that it is stationary.

    filter_rates_id = adf_df[~(adf_df['null']) & (adf_df['units_short'].str.contains('%'))].index
    filter_level_id = adf_df[~(adf_df['null']) & (~adf_df['units_short'].str.contains('%'))].index

    # Real Gross Domestic Product, Real gross domestic product per capita, Real Potential Gross Domestic Product
    # Check

    for id in df.columns:
        df_clean = df[id].dropna()
        if id in filter_rates_id:
            df[id] = df_clean.diff().reindex(df.index)
        elif id in filter_level_id:
            df[id] = np.log(df_clean).diff().reindex(df.index)
        else: 
            df[id] = df_clean.reindex(df.index)

    return df

In [ ]:
mapdf = pd.DataFrame()
output = adf_test(mom_data,mapdf)
final = difference(mom_data, output)
final

In [14]:
output.iloc[20:]

,ADF,pvalue,usedlag,nobs,critical_values,icbest,null
ret_24_1,-2.360181,1.532916e-01,0.0,35.0,-2.94851,2.495893,False
ret_18_1,-2.411759,1.384451e-01,0.0,35.0,-2.94851,2.438792,False
ret_12_0,-2.515610,1.117222e-01,0.0,35.0,-2.94851,2.588340,False
ret_9_1,-2.582699,9.662596e-02,0.0,35.0,-2.94851,2.780318,False
ret_6_0,-2.853462,5.103353e-02,0.0,35.0,-2.94851,2.506239,False
ret_9_0,-2.868608,4.912215e-02,1.0,34.0,-2.95123,1.854720,True
ret_6_1,-3.146175,2.331941e-02,0.0,35.0,-2.94851,3.004887,True
resff3_12_1,-3.388262,1.136558e-02,0.0,35.0,-2.94851,3.385926,True
ret_12_7,-3.398248,1.101873e-02,1.0,34.0,-2.95123,1.725820,True
resff3_6_1,-3.694368,4.193068e-03,0.0,35.0,-2.94851,3.622259,True
ret_2_0,-5.218612,8.054547e-06,1.0,34.0,-2.95123,2.463831,True
ret_3_1,-5.499564,2.086068e-06,1.0,34.0,-2.95123,2.294808,True
ret_3_0,-5.533905,1.762303e-06,1.0,34.0,-2.95123,3.137693,True
International,-5.836762,3.860289e-07,0.0,35.0,-2.94851,5.770885,True
U.S. Small Cap,-6.137505,8.119900e-08,0.0,35.0,-2.94851,6.116665,True
U.S. Large Cap,-6.596523,6.903413e-09,0.0,35.0,-2.94851,6.686953,True
UMD,-7.070526,4.950904e-10,0.0,35.0,-2.94851,6.521442,True